# Generated by Django 6.0 on 2025-12-23 16:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_agency_current_subscription'),
        ('agency', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agencysubscription',
            name='agency',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription_record', to='accounts.agency'),
        ),
    ]
